### ISSUE TITLE
TF modules pinning notes

### ISSUE THREAD

**Issue by MaxymVlasov** [lacework/terraform-aws-cloudtrail#128]
That's a kind of "latest" pin

https://github.com/lacework/terraform-aws-cloudtrail/blob/006c2f3f92f882e70e5339fe8fb2038398fd4756/main.tf#L617-L619

In case, if something will be broken in version `0.9999` - all module versions from the time when `version = "~> 0.3"` was introduced will become broken without any changes to the code.

Which is a little bit violating https://reproducible-builds.org/ (a little bit, because the main reason this site is not about infra at all)

Regarding [TF best practices](https://developer.hashicorp.com/terraform/language/expressions/version-constraints#module-versions):

>For modules maintained within your organization, specifying version ranges may be appropriate if semantic versioning is used consistently or if there is a well-defined release process that avoids unwanted updates.

it +- okay, because you manage both modules, and if you have cross-module change testing CI somewhere.

But if not - better not to have such floating stuff for modules. And update versions when you need or, automate these updates by Renovate/dependabot. For example, here is a quick start solution - https://github.com/SpotOnInc/renovate-config/.

**Comment by robert-mcclary-1uphealth** [comment]
Just dug around a bunch of external dependencies and noticed that this is what is causing something have contraints mismatch when attempting to use the lacework provider pinned at a certain version. 

For instance we are pinning to version  ~> 0.2, ~>0.25 (which don't conflict but work out to be 0.27.0) because we are not ready to jump to aws provider >4.0.

```
module "lacework_config" {
    source  = "lacework/config/aws"
    version = "0.7"
}

module "lacework_cloudtrail" {
    source = "lacework/cloudtrail/aws"
    version = "1.0.2"
}
```

However, since late last week there was an update to the `lacework/iam-role/aws` (which is sourced within the cloudtrail `lacework/cloudtrail/aws` module that is versioned as 0.4.1 which is within the current ~> 0.1 that our older 1.0.2 version cloudtrail module sources which creates a dependency on ~> 1.0, ~> 1.15 provider which is conflicting with the current attempt to pin at ~> 0.2 (0.27.0) and outputting an error when doing a terragrunt init due to the collision of version requirements. 

`Could not retrieve the list of available versions for provider lacework/lacework: no available releases match the given constraints 0.27.0, ~> 1.0, ~> 1.15`

And because this is an external dependency within the cloudtrail module we cannot change/update this without forking and setting this to be different at the moment.

**Comment by afiune** [comment]
@MaxymVlasov Thank you so much for your feedback, the team is looking into this issue actively. I will come back to you with some updates soon.

**Comment by afiune** [comment]
@robert-mcclary-1uphealth Thank you so much for such detailed feedback. Also, apologies for the troubles.

We are about to hit the one year mark from the release of [v0.27.0 of our provider](https://github.com/lacework/terraform-provider-lacework/releases/tag/v0.27.0), this version still uses some APIv1 endpoints that are about to be decommissioned in November 2023 (next month), I highly encourage you to do update to the latest version, or at least jump to [v1.0.0](https://github.com/lacework/terraform-provider-lacework/releases/tag/v1.0.0).

Having said that, we acknowledge that we have put you in a bad spot here since you have no way to continue using the versions you were using. 😞 

I am going to work on releasing two more versions of both modules to unblock you with @MaxymVlasov recommendation. Once again, we apologize for the inconveniences.

**Comment by afiune** [comment]
@robert-mcclary-1uphealth here you have them:

* https://github.com/lacework/terraform-aws-config/releases/tag/v0.7.2
* https://github.com/lacework/terraform-aws-cloudtrail/releases/tag/v1.0.3

-- Please, let me know if these versions unblock you. 

<img src="https://media4.giphy.com/media/KJ1f5iTl4Oo7u/giphy-downsized-medium.gif"/>

**Comment by afiune** [comment]
Please, feel free to re-open this issue if this hasn't been solved.
